services:
    # DJANGO APP
    backend:
        container_name: django
        build: .
        command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - django_redis

    # Redis
    django_redis:
        container_name: django_redis
        image: redis
        ports:
            - "6379:6379"

    # Database
    django_db:
        container_name: postgresql
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: django
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: django_db
        ports:
            - "5432:5432"
        volumes:
            - .dbdata:/var/lib/postgresql
